# Timeline and roadmap

## Medium term goals (~1 year)

* General web presence
    - Register domain name, Discord server and Twitter handle: Done
    - Create GitLab repo and webpage: Done
    - Publication of the Version 0 draft manifesto for 'a Science Collective': Done 
* Build community to fill necessary roles
* Organize and run introduction and brainstorming session (25-11-2021 at 16:00 CET)
    - Identification of areas that lack detail, focus or definition.
* Organize and run broader half-day online conference/workshop.
    - Tasks:
        - Define agenda, speakers, workshops
        - Send out invitations to speak at half-day online conference.
    - Initial list of possible topics:
        - Better publication, 
        - Who needs peer review anyway?
        - Easy steps to improve reproducibility / replicability practices
        - Funding of autonomous research
        - How to build community
        - Education
        - Autonomous data collection
        - Governance of the Science-Collective
        - Building resources for the Science-Collective
        - Definition of concrete showcase projects
* Work together on projects to refine and develop collaboration standards
and guidelines
* Update manifesto based on wider review and feedback: V0.1

## Longer Term

* Start fleshing out the Bookdown site with:
  - More outward links and references
  - Further edits to Vision, Mission and more time planning
  - More detailed description and specification of the plans and showcase projects
  - Add graphs, pictures and illustrations to make the site more friendly to read and to illustrate key parts of the narrative. E.g. the research cycle and the cycle from data to knowledge graphs and back

* Other tasks:
  - Outline the different tools that we envision and set out priorities for their development
  - Outline the tools / environments we aim to focus on in the short / medium term: R, blogdown, bookdown, GitHub, (Twitter/Youtube?/Discord?/Colony?)
  - Brainstorm requirements for tool inter-operability
  - Write out a clear set of principles we adhere to, define (or find, review and edit) a code of conduct for 'a Science Collective'
  - Make a document outlining options for internal organisation and governance models, including Blockchain based structures for decentralised autonomous organisations (DAOs)
  - Explore options for sustainable funding for 'a Science Collective', particularly the possibility to raise funding through blockchain-issued tokens linked to the governance DAO
  - Read background on all the different dimensions/problems/solutions we touch on and make a review of theory, current approaches and start building a reference base
  - Explore if there is sufficient interest for a reading/jounal club or a regular lecture series
  - Start exploring and linking to other groups and initiatives that have aligned objectives
  - Start developing specific documentation of internal processes and onboarding materials
  - Start developing educational materials at different levels
